stages:
  #  - build_debug
  - build_release
  #  - test
  - deploy


before_script:
  - echo $PATH
  - echo $(pwd)


# templates
.vendor_up: &VENDOR_UP
  script:
    - echo $(pwd)
    - echo $MSYSTEM
    - echo $CI_PROJECT_DIR
    - echo $TARGET_DIR
    - export BSVENDOR_LOG_LEVEL=DEBUG
    - export BSBUILD_LOG_LEVEL=DEBUG
    - export BSBUILD_SRC_PATH=$TARGET_DIR
    - echo $BSBUILD_SRC_PATH
    - chmod u+x ./$BSVENDOR
    - ./$BSVENDOR
    - ./update_cmake-macro.sh
    - $BSBUILD --config=$BSBUILD_CFG


#
# Mac
#
release_64_osx:
  stage: build_release
  tags: [mac]
  variables:
    TARGET_DIR: $CI_PROJECT_DIR
    BSVENDOR: vendor-mac.sh
    BSBUILD: bsbuild
    BSBUILD_CFG: "build-mac-release.toml"
  <<: *VENDOR_UP