[build]
prefix = "/Volumes/data01/02_cppbuild"

[[lib]]
name = "curlpp"
build-type = "release"
src = "/Volumes/data01/00_dev/project/curlpp"
test = false
install = true
make-parallel-opt = "-j4"

cmake-definitions = [
    "CMAKE_VERBOSE_MAKEFILE:BOOL=ON",
    "CURL_ROOT=/usr/local/opt/curl-openssl",
    "OPENSSL_ROOT_DIR=/usr/local/opt/openssl",
    "NGHTTP2_CUSTOM_PATH=/usr/local/opt/nghttp2",
]
